language: ruby
dist: trusty
cache: bundler

script: bundle exec rspec

matrix:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: "3.0"
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: truffleruby
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
