name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
          - os: ubuntu
            ruby: "2.7"
            proxy: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Prepare squid
      if: matrix.proxy
      env:
        PROXY_URL: "http://localhost:3128"
      run: |
        sudo apt-get install squid
        sudo systemctl start squid
    
    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec rspec
